DevMicwalis/Models/ContactFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DevMicwalis.Models
{
    public class ContactFormViewModel
    {
        [Required]
        public string Name { get; set; }
        [Required, Display(Name = "Email Address"), EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

DevMicwalis/Controllers/ContactFormSurfaceController.cs
using DevMicwalis.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using System.Net;

namespace DevMicwalis.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactFormViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleFormSubmit(ContactFormViewModel model)
        {

            if (!ModelState.IsValid)
            {
                TempData["EmailSent"] = false;
                return RedirectToCurrentUmbracoPage();
            }


            var body = "<h4>From:</h4><p>{0}</p><h4>Email:</h4><p>{1}</p><h4>Message:</h4><p>{2}</p>";
                MailMessage message = new MailMessage();
                message.To.Add("contactdev@walterbueso.us");
                message.Subject = "New contact form submission from Micwalis Website";
                message.Body = string.Format(body, model.Name, model.Email, model.Message);
                message.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Send(message);

            TempData["EmailSent"] = true;


            return RedirectToCurrentUmbracoPage();

           
           
        }
    }
}

DevMicwalis/Views/About.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}
<header class="main-header">
    <div class="container">
        <h1 class="page-title">About us</h1>

        <ol class="breadcrumb pull-right">
            <li><a href="/">Home</a></li>
            
            <li class="active">About us</li>
        </ol>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="right-line no-margin-top">Micwalis</h2>
        </div>
        <div class="col-md-8 wow fadeInUp">
            @*<h2 class="right-line">Micwalis</h2>*@
            @Umbraco.Field("bodyText")
            @*<hr class="dotted">
            <blockquote class="blockquote-color-bg-primary">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sodales sagittis magna. consectetur adipiscing elit sed consequat, leo eget bibendum sodales.</p>
                <footer>Adrián Guerra Marrero, Artificial Reason CEO</footer>
            </blockquote>*@
        </div>
        <div class="col-md-4 wow fadeInUp">
            
            <div class="panel panel-primary">
                <div class="panel-heading"><h3 class="panel-title">Services</h3></div>
                <div class="panel-body" style="padding-bottom:0;">
                    <ul class="list-group about" style="margin-bottom:0;">
                        <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Carpet Cleaning</li>
                        <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Hardwood Cleaning</li>
                        <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Window Washing</li>
                        <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Office Building</li>
                        <li class="list-group-item"><i class="fa fa-check" aria-hidden="true"></i> Residential Cleaning</li>
                    </ul>
                    <div class="pricing-box-footer"><a href="#" class="btn btn-ar btn-primary">Learn More</a></div>
                    
                </div>
            </div>
            
            @*<h2 class="right-line">Our clients</h2>
            <div class="row">
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/intel.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/microsoft.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/nokia.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/samsung.png" alt="" class="img-responsive"></div>
            </div>
            <div class="row">
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/anz.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/maxis.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/sony.png" alt="" class="img-responsive"></div>
                <div class="col-md-6 col-sm-3 col-xs-6"><img src="~/assets/img/demo/hp.png" alt="" class="img-responsive"></div>
            </div>*@
        </div>
    </div> <!-- row -->
    <div class="row">
        <div class="col-md-12">
            <h2 class="right-line">Our Team</h2>
        </div>
        <div class="col-md-6">
            <section>
                <div class="panel panel-default  animated fadeInDown animation-delay-8">
                    <div class="panel-body">
                        <h3 class="section-title no-margin-top">Deano Barnes <small class="pull-right">Founder</small><div class="clearfix"></div></h3>
                        <div class="clearfix"></div>
                        <img src="~/assets/img/demo/t3.jpg" alt="" class="alignleft imageborder">
                        <p class="no-margin-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, explicabo, impedit, voluptatibus fugiat saepe mollitia modi ab itaque cumque perferendis aut ducimus voluptas enim. Aspernatur, nobis id molestias! Quas, beatae commodi voluptates qui sed sint eos magni perferendis! Ea, necessitatibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, illum dolor alias provident officiis. Neque at accusamus quis provident delectus commodi voluptates.</p>
                        <div class="clearfix"></div>
                        <a href="#" class="social-icon-ar sm twitter animated fadeInDown"><i class="fa fa-twitter"></i></a>

                        <a href="#" class="social-icon-ar sm facebook animated fadeInDown"><i class="fa fa-facebook"></i></a>

                        <a href="#" class="social-icon-ar sm linkedin animated fadeInDown"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </section>
        </div>
        <div class="col-md-6">
            <section>
                <div class="panel panel-default  animated fadeInDown animation-delay-11">
                    <div class="panel-body">
                        <h3 class="section-title no-margin-top">Michael Grant <small class="pull-right">Founder</small><div class="clearfix"></div></h3>
                        <div class="clearfix"></div>
                        <img src="~/assets/img/demo/t6.jpg" alt="" class="alignleft imageborder">
                        <p class="no-margin-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, explicabo, impedit, voluptatibus fugiat saepe mollitia modi ab itaque cumque perferendis aut ducimus voluptas enim. Aspernatur, nobis id molestias! Quas, beatae commodi voluptates qui sed sint eos magni perferendis! Ea, necessitatibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, illum dolor alias provident officiis. Neque at accusamus quis provident delectus commodi voluptates.</p>
                        <div class="clearfix"></div>
                        <a href="#" class="social-icon-ar sm twitter animated fadeInDown"><i class="fa fa-twitter"></i></a>
                        
                        <a href="#" class="social-icon-ar sm facebook animated fadeInDown"><i class="fa fa-facebook"></i></a>
                        
                        <a href="#" class="social-icon-ar sm linkedin animated fadeInDown"><i class="fa fa-linkedin"></i></a>
                        
                    </div>
                </div>
            </section>
        </div>
        <div class="col-md-6">
            <section>
                <div class="panel panel-default  animated fadeInDown animation-delay-14">
                    <div class="panel-body">
                        <h3 class="section-title no-margin-top">John Doe <small class="pull-right">Position Name</small><div class="clearfix"></div></h3>
                        <div class="clearfix"></div>
                        <img src="~/assets/img/demo/t3.jpg" alt="" class="alignleft imageborder">
                        <p class="no-margin-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, explicabo, impedit, voluptatibus fugiat saepe mollitia modi ab itaque cumque perferendis aut ducimus voluptas enim. Aspernatur, nobis id molestias! Quas, beatae commodi voluptates qui sed sint eos magni perferendis! Ea, necessitatibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, illum dolor alias provident officiis. Neque at accusamus quis provident delectus commodi voluptates.</p>
                        <div class="clearfix"></div>
                        <a href="#" class="social-icon-ar sm twitter animated fadeInDown"><i class="fa fa-twitter"></i></a>

                        <a href="#" class="social-icon-ar sm facebook animated fadeInDown"><i class="fa fa-facebook"></i></a>

                        <a href="#" class="social-icon-ar sm linkedin animated fadeInDown"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </section>
        </div>
        <div class="col-md-6">
            <section>
                <div class="panel panel-default  animated fadeInDown animation-delay-17">
                    <div class="panel-body">
                        <h3 class="section-title no-margin-top">John Doe <small class="pull-right">Position Name</small><div class="clearfix"></div></h3>
                        <div class="clearfix"></div>
                        <img src="~/assets/img/demo/t6.jpg" alt="" class="alignleft imageborder">
                        <p class="no-margin-top">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis, explicabo, impedit, voluptatibus fugiat saepe mollitia modi ab itaque cumque perferendis aut ducimus voluptas enim. Aspernatur, nobis id molestias! Quas, beatae commodi voluptates qui sed sint eos magni perferendis! Ea, necessitatibus.</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, illum dolor alias provident officiis. Neque at accusamus quis provident delectus commodi voluptates.</p>
                        <div class="clearfix"></div>
                        <a href="#" class="social-icon-ar sm twitter animated fadeInDown"><i class="fa fa-twitter"></i></a>

                        <a href="#" class="social-icon-ar sm facebook animated fadeInDown"><i class="fa fa-facebook"></i></a>

                        <a href="#" class="social-icon-ar sm linkedin animated fadeInDown"><i class="fa fa-linkedin"></i></a>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div> <!-- container -->

DevMicwalis/Views/Contact.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Contact Us</h1>

        <ol class="breadcrumb pull-right">
            <li><a href="#">Home</a></li>
            
            <li class="active">Contact Us</li>
        </ol>
    </div>
</header>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title no-margin-top">Send Message</h2>
        </div>
        <div class="col-md-8">
            <section>
                <p>Lorem ipsum Ex aliqua tempor nisi laboris dolor id laborum irure minim tempor in sit dolore amet sit esse nostrud tempor nulla consequat aute in nostrud laboris sint ullamco amet nisi pariatur officia nulla pariatur in id et labore dolore ad sit.</p>

                @Html.Action("Index", "ContactFormSurface")
            </section>
        </div>

        <div class="col-md-4">
            <section>
                <div class="panel panel-primary">
                    <div class="panel-heading"><i class="fa fa-envelope-o"></i> Additional Information</div>
                    <div class="panel-body">
                        <h4 class="section-title no-margin-top">Contacts</h4>
                        <address>
                            <strong>Open Mind, Inc.</strong><br>
                            795 Folsom Ave, Suite 600<br>
                            San Francisco, CA 94107<br>
                            <abbr title="Phone">P:</abbr> (123) 456-7890 <br>
                            Mail: <a href="#">support@openmid.com</a>
                        </address>

                        <!-- Business Hours -->
                        <h4 class="section-title no-margin-top">Business Hours</h4>
                        <ul class="list-unstyled">
                            <li><strong>Monday-Friday:</strong> 9am to 7pm</li>
                            <li><strong>Saturday:</strong> 9am to 2pm</li>
                            <li><strong>Sunday:</strong> Closed</li>
                        </ul>
                    </div>
                </div>
            </section>
        </div>
    </div>

    <hr class="dotted">

    @*<section>
        <div class="well well-sm">
            <iframe width="100%" height="350" src="http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=central%2Bpark&ie=UTF8&z=12&t=m&iwloc=near&output=embed"></iframe>
        </div>
    </section>*@
</div> <!-- container -->

DevMicwalis/Views/Gallery.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}
<header class="main-header">
    <div class="container">
        <h1 class="page-title">Before & After Gallery</h1>

        <ol class="breadcrumb pull-right">
            <li><a href="#">Home</a></li>
            <li class="active">Gallery</li>
        </ol>
    </div>
</header>

<div class="col-xs-12">
    <p class="slogan text-center animated bounceInLeft animation-delay-12">Cras scelerisque enim ac leo molestie consequat.<br> Curabitur sit amet lectus maximus cursus turpis a, posuere tortor.</p>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="row" id="Container">
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img01.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img01.jpg" data-lightbox="image-1" class="animated fadeInDown"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img02.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img02.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img03.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img03.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img04.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img03.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img05.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img04.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img06.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img06.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img07.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img07.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img08.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img08.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="img-caption-ar">
                        <img src="~/assets/img/demo/img09.jpg" class="img-responsive" alt="Image">
                        <div class="caption-ar">
                            <div class="caption-content">
                                <a href="~/assets/img/demo/img09.jpg" class="animated fadeInDown" data-lightbox="image-1"><i class="fa fa-search"></i>Full size</a>
                                <h4 class="caption-title">Title Work</h4>
                            </div>
                        </div>
                    </div>
                </div>
               
            </div>
        </div> <!-- col-md-9 -->
    </div>
</div> <!-- container -->

@section css {
    <link href="~/LightBox/css/lightbox.min.css" rel="stylesheet" />
}
@section js {
<script src="~/LightBox/js/lightbox.min.js"></script>    
}

DevMicwalis/Views/Partials/ContactForm.cshtml
@model DevMicwalis.Models.ContactFormViewModel

@using (Html.BeginUmbracoForm<DevMicwalis.Controllers.ContactFormSurfaceController>("HandleFormSubmit"))
{
    @Html.AntiForgeryToken()
    if (TempData["EmailSent"] != null && (bool)TempData["EmailSent"])
    {
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong><i class="fa fa-check"></i></strong> Thank you for contacting us! We will respond to you shortly.
        </div>
    }
    else if (TempData["EmailSent"] != null && (bool)TempData["EmailSent"] == false)
    {
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong><i class="fa fa-times"></i> Error!</strong> Sorry something went wrong. Please try again.
        </div>
    }
    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Name)

    </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email)

        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Message)
            @Html.TextAreaFor(m => m.Message, new { @class = "form-control", rows = "8" })
            @Html.ValidationMessageFor(m => m.Message)
        </div>

        <button type="submit" class="btn btn-ar btn-primary">Submit</button>
}


<div class="clearfix"></div>

DevMicwalis/Views/Partials/ContactSecond.cshtml
@model DevMicwalis.Models.ContactFormViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ContactFormViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DevMicwalis/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

DevMicwalis/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

DevMicwalis/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

DevMicwalis/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

DevMicwalis/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.TextPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}